from fastapi import FastAPI
from pydantic import BaseModel
from dotenv import load_dotenv
import os

load_dotenv()

app = FastAPI(title="LLM-Powered SQL Agent (Sanitized)")

class QueryInput(BaseModel):
    question: str

@app.post("/ask")
async def ask_query(payload: QueryInput):
    """
    NOTE:
    Core agent logic, system prompts, and database schema
    are intentionally omitted due to client confidentiality.
    """
    return {
        "success": True,
        "question": payload.question,
        "answer": {
            "text": "Response generated by a LangGraph-based LLM agent (logic omitted for confidentiality)."
        }
    }
